-
  name: Boutique Hostel Forum
  href: https://hostelforumzadar.com/en
-
  name: Guesthouses I and II
  href: http://gostinjacbsm.com/guesthouses-zadar
-
  name: Youth Hostel, University of Zadar
  href: http://www.unizd.hr/studentskidom/english
-
  name: Youth Hostel Zadar
  href: https://www.tripadvisor.com/Hotel_Review-g295374-d602003-Reviews-Youth_Hostel_Zadar-Zadar_Zadar_County_Dalmatia.html
-
  name: Airbnb
  href: https://www.airbnb.com
-
  name: Booking.com
  href: https://www.booking.com
