-
  date: 09-16-2020
  events:
    -
      from: '10:00'
      to: '14:00'
      type: Webinar
      title: National Capacity Building NI4OS Europe Training
      href: https://events.ni4os.eu/event/16/timetable/#20200916.detailed
      video: https://www.youtube.com/watch?v=N0Xjcf4cr54&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=1
    -
      from: '12:00'
      to: '12:45'
      type: Workshop 1
      id: good-practices-in-academic-writing
      video: https://www.youtube.com/watch?v=Gd1Yu4Pge1w&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=2&t=1s
    -
      from: '12:00'
      to: '12:45'
      type: Workshop 2
      id: plumx-metrics
      video: https://www.youtube.com/watch?v=j7PTj7yQ0A8&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=3&t=5s
    -
      from: '12:45'
      to: '13:00'
      title: Coffee/tea break
    -
      from: '13:00'
      to: '13:45'
      type: Workshop 3
      id: fair-data
      video: https://www.youtube.com/watch?v=sXS3BGjSuDw&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=4&t=1s
    -
      from: '13:45'
      to: '14:00'
      title: Coffee/tea break
    -
      type: Session P1
      title: OPERAS
      organizer: Open scholarly communication in Europe (OPERAS)
      video: https://www.youtube.com/watch?v=c_YBRXGDjoU&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=5
      moderators:
        - name: Jadranka Stojanovski
          affiliation: University of Zadar / Ruđer Bošković Institute
      events:
        -
          from: '14:00'
          to: '15:30'
          id: scholarly-communication
        - id: inclusive-scholarly-communication-infrastructure
    -
      from: '15:30'
      to: '15:45'
      title: Coffee/tea break
    -
      type: Session P2
      title: SPARC Europe
      organizer: SPARC Europe
      video: https://www.youtube.com/watch?v=3EqIOF_OkkE&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=6&t=2s
      moderators:
        - name: Zrinka Pongrac Habdija
          affiliation: Faculty of Food Technology and Biotechnology
      events:
        -
          from: '15:45'
          to: '17:15'
          title: Highlights from SPARC Europe
          speakers:
            - id: vanessa-proudman
        -
          title: Priorities for the path ahead including hints on our next 4 year strategy
          speakers:
            - id: vanessa-proudman
        -
          title: Open science and the new Directive on copyright in the internal market 2019/790
          speakers:
            - id: romana-matanovac-vuckovic
        -
          title: "Publisher Copyright and Licensing Policies: Findings. Work commissioned by SPARC Europe (an Open Discussion on Copyright and Licensing Policy Recommendations)"
          speakers:
            - id: ignasi-labastida-i-juan
    -
      from: '17:15'
      to: '17:30'
      title: Coffee/tea break
    -
      type: Session R1
      title: The European Association of Science Editors (EASE)
      moderators:
        - name: Zrinka Pongrac Habdija
          affiliation: Faculty of Food Technology and Biotechnology
      events:
        -
          from: '17:30'
          to: '18:00'
          id: supporting-the-professional-development-of-editors-with-ease
    -
      type: Session P3
      title: PUBMET2020 Short Talk Session (peer reviewed)
      video: https://www.youtube.com/watch?v=n1glrcGfe2o&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=7
      moderators:
        - name: Lea Škorić
          affiliation: University of Zagreb School of Medicine
        - id: kresimir-zauder
      events:
        -
          from: '15:45'
          to: '18:00'
          type: Part 1
          title: Reinventing Scholarly Publishing
          events:
            - id: reinventing-scientific-journals
            - id: innovation-in-scholarly-publishing
            - id: the-modular-publishing-unit
            - id: recommendations-for-transparency
            - id: editorial-and-peer-review-policy
        -
          type: Part 2
          title: Supporting Open Science
          events:
            - id: is-your-metadata-a-unicorn
            - id: implementation-of-e-learning-in-croatian-high-education-institutions
            - id: differences-in-openness-and-sharing
-
  date: 09-17-2020
  events:
    -
      from: '10:00'
      to: '10:15'
      title: Conference Opening
      class: font-bold
      video: https://www.youtube.com/watch?v=3_HzGHC74xM&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=8
    -
      from: '10:15'
      to: '10:30'
      title: In tribute to Jon Tennant
      class: font-bold
    -
      from: '10:30'
      to: '11:00'
      type: Keynote 1
      id: plan-s
      video: https://www.youtube.com/watch?v=fRY1-TlVYAE&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=9
    -
      type: Session 1
      location: Zagreb
      video: https://www.youtube.com/watch?v=qx6dQx2dAbI&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=10
      moderators:
        - name: Danijel Namjesnik
          affiliation: Faculty of Science, University of Zagreb
        - name: Iva Grabarić Andonovski
          affiliation: Faculty of Food Technology and Biotechnology, University of Zagreb
      events:
        -
          from: '11:00'
          to: '12:15'
          type: Panel Session 1
          id: small-national-publishers-journals
    -
      from: '12:15'
      to: '12:30'
      title: Coffee/tea break
    -
      type: Session 2
      location: Split
      organizer: School of Medicine at University of Split and University of Split Library
      video: https://www.youtube.com/watch?v=qHnTMiRNIXM&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=11
      moderators:
        - name: Mirta Matošić
          affiliation: University of Split Library
      events:
        -
          from: '12:30'
          to: '13:15'
          id: publication-integrity
        -
          from: '13:15'
          to: '13:30'
          title: Q&A

    -
      from: '13:30'
      to: '14:00'
      title: Lunch break
    -
      from: '14:00'
      to: '14:30'
      type: Keynote 2
      id: open-access-publishing
      video: https://www.youtube.com/watch?v=lL0Q9NhsgJQ&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=12
    -
      type: Session 3
      location: Zagreb
      organizer: University Computing Centre SRCE, University of Zagreb
      video: https://www.youtube.com/watch?v=4nqND4AIUtE&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=13
      moderators:
        - id: drazenko-celjak
      events:
        -
          from: '14:30'
          to: '15:30'
          title: Connecting National OA Publishing Platform With National (Data) Repository Platform
          events:
            - id: biochemia-medica-and-research-data
            - id: infrastructure-for-open-science
            - id: research-data-policies-for-croatian-journals
            - id: how-to-manage-research-data
        -
          from: '15:30'
          to: '15:45'
          title: Q&A
    -
      from: '15:45'
      to: '16:00'
      title: Coffee/tea break
    -
      from: '16:00'
      to: '16:30'
      type: Keynote 3
      id: local-to-global
      video: https://www.youtube.com/watch?v=ksyCUEZykEw&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=14
    -
      from: '16:30'
      to: '16:45'
      title: Q&A
    -
      from: '16:45'
      to: '17:00'
      title: Coffee/tea break
    -
      type: Session 4
      location: Novi Sad
      organizer: University of Novi Sad, Serbia
      video: https://www.youtube.com/watch?v=IJtQFX566rg&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=15
      moderators:
        - name: Iva Melinščak Zlodi
          affiliation: Faculty of Social Sciences and Humanities, University of Zagreb
      events:
        -
          from: '17:00'
          to: '18:00'
          id: open-access-to-scientific-results-at-university-of-novi-sad
          events:
            -
              from: '17:00'
              to: '17:20'
              title: Digital Library of Doctoral Dissertations Defended at the University of Novi Sad
              speakers:
                - id: mirjana-brkovic
            -
              from: '17:20'
              to: '17:40'
              title: Analysis of the usage of open access dissertations
              speakers:
                - id: ljubomir-paskali
            -
              from: '17:40'
              to: '18:00'
              title: Institutional repository of scientific publications at University of Novi Sad
              speakers:
                - id: branko-milosavljevic
            -
              from: '18:00'
              to: '18:15'
              title: Q&A
-
  date: 09-18-2020
  events:
    -
      from: '09:00'
      to: '09:30'
      keynote: true
      type: Keynote 4
      title: The French National Open Science Plan. A national contribution to an international open science vision
      video: https://www.youtube.com/watch?v=SUxNlxhV1vY&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=16
      speakers:
        - id: marin-dacos
      moderators:
        - name: Jadranka Stojanovski
          affiliation: University of Zadar / Ruđer Bošković Institute
    -
      type: Session 5
      location: Zadar
      video: https://www.youtube.com/watch?v=xIjWJXVQxzA&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=17
      moderators:
        - id: vladimir-mrsa
        - name: Franjo Pehar
          affiliation: Department of Information Sciences of the University of Zadar
      events:
        -
          from: '09:30'
          to: '10:45'
          id: os-policies-os-evaluation-and-assessment-supporting-os-publishing
    -
      from: '10:45'
      to: '11:00'
      title: Coffee/tea break
    -
      type: Session 6
      location: Ljubljana
      organizer: Centralna tehniška knjižnica, Ljubljana, Slovenija
      video: https://www.youtube.com/watch?v=vY_XHMG9GMI&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=18
      moderators:
        - id: miro-pusnik
      events:
        -
          from: '11:00'
          to: '12:00'
          id: slovenian-research-infrastructure
        -
          from: '12:00'
          to: '12:15'
          title: Q&A
    -
      from: '12:15'
      to: '12:30'
      title: Coffee/tea break
    -
      type: Session 7
      location: Skopje
      organizer: Metamorphosis, Foundation for Internet and Society, Macedonia
      video: https://www.youtube.com/watch?v=K8dpsZvQPqU&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=19
      moderators:
        - name: Bardhyl Jashari
          affiliation: Metamorphosis, Foundation for Internet and Society
      events:
        -
          from: '12:30'
          to: '13:15'
          title: Challenges to Open and Online Education in North Macedonia
          presenters:
            - id: zoran-janevski
            - id: sead-dzigal
            - id: goce-arsovski
        -
          from: '13:15'
          to: '13:30'
          title: Q&A
    -
      from: '13:30'
      to: '13:45'
      title: Coffee/tea break
    -
      type: Session 8
      location: Sarajevo
      organizer: University of Sarajevo, Bosnia and Herzegovina
      video: https://www.youtube.com/watch?v=UKqX4i_PcpA&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=20
      moderators:
        - id: sasa-madacki
      events:
        -
          from: '13:45'
          to: '14:45'
          id: ethics-integrity-and-transparency
        -
          from: '14:45'
          to: '15:00'
          title: Q&A
    -
      from: '15:00'
      to: '15:15'
      title: Coffee/tea break
    -
      type: Session 9
      location: Sponsors
      video: https://www.youtube.com/watch?v=I-Dlp_6lEp0&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=21
      events:
        -
          from: '15:15'
          to: '15:45'
          title: PUBMET2020 sponsors' session
          events:
            - title: Elsevier
              description: The usage of Elsevier Digital Commons to see what small but ambitious universities do in the area of research publishing, measurement and evaluation.
              speakers:
                - name: Dr. Edmond Hajrizi
                  affiliation: University for Business and Technology
            - title: Clarivate
              speakers:
                - name: Josef Jilek
                  affiliation: Solution specialist at Clarivate Analytics
    -
      type: Session 10
      location: Osijek
      organizer: Department of Information Sciences, Faculty of Philosophy, JJ. Strossmayer University
      video: https://www.youtube.com/watch?v=c686cH3k-D8&list=PLi0ZIylnKSTu_5TNN1G3Mzvr9W38-jlDA&index=22
      moderators:
        - id: kresimir-zauder
      events:
        -
          from: '16:00'
          to: '17:00'
          id: publishing-in-lockdown
        -
          from: '17:00'
          to: '17:15'
          title: Q&A
    -
      from: '17:15'
      to: '17:30'
      title: Conference closure
      class: font-bold
