url: http://pubmet.unizd.hr
year: 2020
description: The 7th Conference on Scholarly Communication and Publishing in the Context of Open Science
email: pubmet@unizd.hr
registrationUrl: https://docs.google.com/forms/d/e/1FAIpQLScs2sau6fvum3pi9Ic2XTkMVx7cAb2e-NjRPKJ-Fx807NvxSA/viewform
trackingId: UA-27463615-3
